# START BY PULLING THE PYTHON IMAGE
FROM python:3.7

# COPY THE REQUIREMENTS FILE INTO THE IMAGE
COPY ./requirements.txt /requirements.txt

# SWITCH WORKING DIRECTORY
WORKDIR ./

# INSTALL THE DEPENDENCIES AND PACKAGES IN THE REQUIREMENTS FILE
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
# RUN pip install -e .

# COPY EVERY CONTENT FROM THE LOCAL FILE TO THE IMAGE
COPY . /

EXPOSE 8080

# CONFIGURE THE CONTAINER TO RUN IN AN EXECUTED MANNER
ENTRYPOINT [ "python" ]

CMD ["app.py" ]