version: '3.7'

services:

  app:
    # CHANGE [IMAGE, CONTAINER_NAME, VOLUMES, AND PORT] TO MATCH THE PROJECT
    # ALSO CHANGE FOLDER IN '.dockerignore' TO MATCH VOLUME
    image: "base_flask_project"
    container_name: "base_flask_project"
    volumes:
      - /data_base_flask_project:/data_base_flask_project:z
    ports:
      - '5001:5000'
    restart: always